profile: k8s
imageRepository: terrytantan
servers:
  - configServer:
      replicas: 1
      appName: config-server
      deploymentName: config-server-deployment
      serviceName: config-server
      containerName: config-server
      port: 8888
      image:
        name: spring-petclinic-config-server
        tag: latest
  - discoveryServer:  
      replicas: 1
      appName: discovery-server
      deploymentName: discovery-server-deployment
      serviceName: discovery-server
      containerName: discovery-server
      port: 8761
      image:
        name: spring-petclinic-discovery-server
        tag: latest
  - openzipkin:
      replicas: 1
      appName: tracing-server
      deploymentName: tracing-server-deployment
      serviceName: tracing-server
      containerName: tracing-server
      port: 9411
      image:
        name: openzipkin/zipkin
        tag: latest
  - adminServer:
      replicas: 1
      appName: admin-server
      deploymentName: admin-server-deployment
      serviceName: admin-server
      containerName: admin-server
      port: 9090
      image:
        name: spring-petclinic-admin-server
        tag: latest
  - apiGateway:
      replicas: 1
      appName: api-gateway
      deploymentName: api-gateway-deployment
      serviceName: api-gateway
      containerName: api-gateway
      port: 8080
      image:
        name: spring-petclinic-api-gateway
        tag: latest
  - customerService:
      replicas: 1
      appName: customers-service
      deploymentName: customers-service-deployment
      serviceName: customers-service
      containerName: customers-service
      port: 8081
      image:
        name: spring-petclinic-customers-service
        tag: latest
  - genaiService:
      replicas: 1
      appName: genai-service
      deploymentName: genai-service-deployment
      serviceName: genai-service
      containerName: genai-service
      port: 8084
      image:
        name: spring-petclinic-genai-service
        tag: latest
  - vetsService:
      replicas: 1
      appName: vets-service
      deploymentName: vets-service-deployment
      serviceName: vets-service
      containerName: vets-service
      port: 8083
      image:
        name: spring-petclinic-vets-service
        tag: latest
  - visitsService:
      replicas: 1
      appName: visits-service
      deploymentName: visits-service-deployment
      serviceName: visits-service
      containerName: visits-service
      port: 8082
      image:
        name: spring-petclinic-visits-service
        tag: latest
ingress:
  name: spring-petclinic-ingress
  annotations:
    rewriteTarget: /
    useRegex: "true"
  className: nginx
  rules:
    - adminServer:
        host: admin.spring-petclinic.com
        path: /
        service:
          name: admin-server
          port: 9090  
    - apiGateway:
        host: spring-petclinic.com
        path: /
        service:
          name: api-gateway
          port: 8080
    - discoveryServer:
        host: discovery.spring-petclinic.com
        path: /
        service:
          name: discovery-server
          port: 8761
    - configServer:
        host: config.spring-petclinic.com
        path: /
        service:
          name: config-server
          port: 8888
    - openzipkin:
        host: tracing.spring-petclinic.com
        path: /
        service:
          name: tracing-server
          port: 9411
