apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.annotations.rewriteTarget }}
    nginx.ingress.kubernetes.io/use-regex: {{ .Values.ingress.annotations.useRegex | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
{{- range $i, $server := .Values.ingress.rules }}
  {{- range $key, $configInfo := $server }}
{{ include "spring-petclinic.ingress-rule" (dict "root" $configInfo "namespace" $.Values.namespace) | indent 4}}
  {{- end }}
{{- end }}